-- Public numeric ids for help-center URLs (`/hc/{locale}/articles/{urlId}-{slug}`).
-- Identity backfills existing rows.
ALTER TABLE "kb_categories" ADD COLUMN IF NOT EXISTS "url_id" integer
  GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS "kb_categories_url_id_idx"
  ON "kb_categories" ("url_id");

ALTER TABLE "kb_articles" ADD COLUMN IF NOT EXISTS "url_id" integer
  GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS "kb_articles_url_id_idx"
  ON "kb_articles" ("url_id");
