/** Image fixtures shared by the deriver and worker tests. */

// A 64x48 HEIC written by libheif's encoder.
export const HEIC_64x48 = Uint8Array.from(
  atob(
    'AAAAHGZ0eXBoZWl4AAAAAG1pZjFoZWl4bWlhZgAAAXxtZXRhAAAAAAAAACFoZGxyAAAAAAAAAABwaWN0AAAAAAAAAAAAAAAA' +
      'AAAAACJpbG9jAAAAAERAAAEAAQAAAAABoAABAAAAAAAAAEYAAAAjaWluZgAAAAAAAQAAABVpbmZlAgAAAAABAABodmMxAAAA' +
      'AA5waXRtAAAAAAABAAAA/GlwcnAAAADcaXBjbwAAAHVodmNDAQQIAAAAAAAAAAAAHvAA/P36+gAADwNgAAEAF0ABDAH//wQI' +
      'AAADAJ24AAADAAAeugJAYQABACpCAQEECAAAAwCduAAAAwAAHqAggQTZbq5Ka5uAhoMCAAADADIAAAMAAhBiAAEABkQBwXPA' +
      'iQAAABNjb2xybmNseAABAA0ABoAAAAAUaXNwZQAAAAAAAABAAAAAQAAAAChjbGFwAAAAQAAAAAEAAAAwAAAAAQAAAAAAAAAC' +
      '////8AAAAAIAAAAQcGl4aQAAAAADCgoKAAAAGGlwbWEAAAAAAAAAAQABBYECAwWEAAAATm1kYXQAAABCKAGvE4D1Zsp2s9Z7' +
      'f+0xWG5viMvluSSssyQFFCs9tLdxauTN9qCeyZKIdyG4sdX3xSpJ0sjWTk6RsMDhqKHTbwxO'
  ),
  (c) => c.charCodeAt(0)
)
