/**
 * Inbound email ingestion. Provider-neutral: `ingestParsedEmail` owns routing
 * and append, and every front door (the Resend webhook via `ingestInboundEmail`,
 * the IMAP poller) normalizes its input to a `ParsedInboundEmail` and feeds it
 * here. A message is routed into a conversation by its plus-address
 * (`<slug>+c<id>.<tag>@domain`) first, then — for replies whose client stripped the
 * plus-address — by matching its In-Reply-To/References against our stored
 * outbound Message-IDs. The visitor's stripped reply is appended through the
 * normal visitor-message path, so lifecycle (reopen), realtime publish and
 * offline notification all behave exactly as they do for a widget message.
 *
 * Auto-generated mail (autoresponders, bounces, list blasts, our own loops) is
 * dropped up front. The caller assumes an already-authenticated payload (the
 * webhook route is Svix-verified; IMAP owns the mailbox) and this never throws
 * on an unroutable one — it returns a status the caller maps to an ack + log.
 */
import { db, eq, sql, conversationMessages, conversations, principal, user } from '@/lib/server/db'
import type { ConversationAttachment, ConversationSpamFiledBy } from '@/lib/server/db'
import type { ConversationId, PrincipalId, TicketId } from '@quackback/ids'
import type { Actor } from '@/lib/server/policy/types'
import { normalizePrincipalType } from '@/lib/server/functions/auth-helpers'
import { isBlocked } from '@/lib/server/domains/principals/blocking'
import { getReceivedEmail } from '@quackback/email'
import { realEmail } from '@/lib/shared/anonymous-email'
import { NotFoundError } from '@/lib/shared/errors'
import { logger } from '@/lib/server/logger'
import {
  parseInboundEmail,
  extractReplyText,
  extractEmailAddress,
  inboundDedupeKey,
  isAutoGeneratedEmail,
  mailLoopSignal,
  normalizeSenderAddress,
  type MailLoopSignal,
  type ParsedInboundEmail,
} from './conversation.email-inbound'
import {
  bearsTicketMarker,
  conversationIdFromInboundAddress,
  ticketIdFromInboundAddress,
  isOwnInboundAddress,
  ownMessageIdDomains,
} from './conversation.email-channel'
import { currentMailSlug } from './conversation.mail-slug'
import { loadTicketOr404 } from '@/lib/server/domains/tickets/ticket.service'
import { appendInboundTicketReply } from '@/lib/server/domains/tickets/requester.service'
import { emailHtmlToContent } from '@/lib/server/content/email-html-to-content'
import { isS3Usable, uploadImageBuffer, MAX_FILE_SIZE } from '@/lib/server/storage/s3'
import {
  storeFile,
  attachmentFromFile,
  FileRejectedError,
} from '@/lib/server/domains/files/files.service'
import { sniffImageMime, canonicalizeImageMime } from '@/lib/server/content/magic-bytes'
import { MAX_CONVERSATION_ATTACHMENTS } from '@/lib/shared/conversation/types'
import {
  resolveConversationByMessageIds,
  resolvePrincipalIdByEmail,
} from './conversation.email-store'
import {
  assertConversationSendRate,
  assertColdInboundRate,
  ConversationRateLimitError,
} from './conversation.ratelimit'
import { sendVisitorMessage } from './conversation.service'
import {
  addressesPlatformInbox,
  ensurePlatformInboundRoute,
  resolveChannelAccountByRecipient,
} from '@/lib/server/domains/channel-accounts/channel-account.service'
import {
  resolveColdInboundSender,
  createEmailConversation,
  cleanupColdInboundLead,
} from './conversation.email-cold-inbound'
import { maybeAutoFileSpam } from './conversation.spam-filter'
import { DEFAULT_LOCALE } from '@/lib/shared/i18n'
import { senderAuthSpamSignal } from './conversation.spam-signals'

export type IngestInboundResult =
  | { status: 'ingested'; conversationId: ConversationId }
  | { status: 'ingested_ticket'; ticketId: TicketId }
  // Refused, but RETAINED: an email conversation exists, filed to Spam with an
  // enumerated cause, out of every triage view and raising no signals. An agent
  // can see it arrived and why, and release it deliberately.
  | { status: 'quarantined'; conversationId: ConversationId; cause: InboundRefusalCause }
  | { status: 'duplicate' }
  | { status: 'no_conversation' }
  // A signed ticket address that resolved but whose target/sender failed a check
  // (unknown/deleted/non-customer ticket, missing requester, sender ≠ requester),
  // or a ticket address whose signature didn't verify. Always dropped — a ticket
  // address never creates a ticket/conversation and never reaches cold inbound.
  | { status: 'no_ticket' }
  | { status: 'empty' }
  | { status: 'from_mismatch' }
  | { status: 'rate_limited' }
  | { status: 'suppressed' }

/**
 * Why this module refused to admit an inbound message — the enumerated
 * vocabulary, so a refusal is queryable rather than a sentence somebody has to
 * grep for.
 *
 * Refusal is an ADMISSION decision and is the only thing this list describes.
 * Whether a message that WAS admitted is spam is a separate judgement made
 * afterwards, and it has its own enumerated vocabulary
 * (CONVERSATION_SPAM_FILED_BY) on the conversation row. Two facts this module
 * observes at admission time are handed to that layer rather than refused here,
 * and end up recorded there instead: a cold auto-responder (files as
 * 'auto_responder') and an ARC-rescued sender (files as
 * 'sender_auth_arc_rescued'). Both are accepted mail, so calling them refusals
 * would make this list mean two different things at once.
 *
 * Of the refusals below, two are retained, and they are the two this module
 * INFERRED rather than observed:
 *
 *   QUARANTINED (retained, reviewable, released by an agent)
 *     sender_auth_reject   hard DMARC fail under p=reject with no validated ARC
 *                          chain. Filed to Spam under the matching cause.
 *     mail_loop_suspected  the message carried a reply address this workspace
 *                          minted, which is what one of our own mails coming
 *                          back looks like once a sending provider has replaced
 *                          our `Message-ID`. That address rides in a header any
 *                          sender controls and everyone we have ever emailed
 *                          holds one, so this is our guess about authorship. A
 *                          wrong guess would be unattributable as well as
 *                          unrecoverable: the log line below carries a cause and
 *                          nothing else, so there would be no id, no sender and
 *                          no subject to match a complaint against.
 *
 *   DROPPED (nothing retained; the log line is the trace)
 *     sender_blocked  the workspace itself blocked this sender. Retaining it
 *                     would undo the block: the agent's own decision was that
 *                     they do not want to see this person's mail, and the trace
 *                     and the recourse are the block record and unblocking it.
 *     rate_limited    over the cold-inbound budget. That throttle's entire job
 *                     is to bound what an unauthenticated stranger can make us
 *                     store, so retaining what it refuses disarms it.
 *     mail_loop       one of our own outbound mails echoing back, on the
 *                     evidence that is a FACT rather than a guess: an id this
 *                     workspace recorded when its own mail went out, or an id on
 *                     a host whose mail is this workspace's own. Retaining our
 *                     own mail is noise at best, and at worst a loop that feeds
 *                     itself. The inferred half of the same question is
 *                     'mail_loop_suspected' above, and it is retained.
 *     auto_generated  machine-generated mail carrying thread context, which
 *                     would otherwise append to a real thread. (A COLD
 *                     auto-responder is not refused — see above.)
 *     empty_body      there is no message to retain.
 *
 * The split is one question: did WE refuse this on the sender's behalf, or did
 * the workspace (or arithmetic) refuse it? We quarantine our own guesses,
 * because a guess about authentication is exactly where a real customer gets
 * destroyed. We do not quarantine somebody else's decision.
 */
export const INBOUND_REFUSAL_CAUSES = [
  'sender_auth_reject',
  'mail_loop_suspected',
  'auto_generated',
  'sender_blocked',
  'rate_limited',
  'mail_loop',
  'empty_body',
] as const
export type InboundRefusalCause = (typeof INBOUND_REFUSAL_CAUSES)[number]

/**
 * A refusal that can be RETAINED: one whose cause is a member of both
 * vocabularies at once.
 *
 * Derived rather than listed, so the two lists are what decide it. A refusal is
 * retained by filing the thread to Spam under its cause, and the Spam view can
 * only badge a cause its own taxonomy knows — so a cause that is not in both is
 * not a cause a retained refusal can carry, and adding one to only one list
 * fails to compile here rather than writing a value nothing can render.
 */
type QuarantineCause = InboundRefusalCause & ConversationSpamFiledBy

const log = logger.child({ component: 'conversation-email-inbound' })

/**
 * Record a refusal. Every path that turns mail away goes through here, so
 * "refused with no trace at all" is not a state this module can reach.
 *
 * The cause is the only thing logged. Deliberately: an address in a log line
 * is a copy of somebody's mail routing sitting in an aggregator, and the
 * recipient address in particular must never be written anywhere.
 */
function logRefusal(cause: InboundRefusalCause, retained: boolean): void {
  log.warn({ cause, retained }, 'inbound email refused')
}

/** Own-storage prefix for inline images rehosted into an email's body. Discrete
 *  attachments go through the file pipeline under its own prefix. */
const INBOUND_IMAGE_PREFIX = 'chat-images'
// Hard ceiling on how many parts a single inbound email may rehost to storage,
// covering inline images AND discrete attachments together. The discrete
// attachment tray is separately capped at MAX_CONVERSATION_ATTACHMENTS; this
// wider budget also bounds cid-referenced inline images (which don't consume an
// attachment slot) so a message stuffed with thousands of tiny inline images
// can't amplify into thousands of uploads.
const MAX_INBOUND_UPLOADS = 25

interface RehostedInboundMedia {
  /** The HTML body with `cid:` references rewritten to rehosted URLs, or the
   *  original html when nothing was rewritten. */
  html: string | undefined
  /** Discrete (non-inline) attachments to carry on the stored message. */
  attachments: ConversationAttachment[]
}

/** Does the HTML reference this Content-ID via a `cid:<id>` URL? */
function htmlReferencesCid(html: string, cid: string): boolean {
  return html.toLowerCase().includes(`cid:${cid.toLowerCase()}`)
}

/**
 * Rewrite every `cid:<id>` reference in the raw HTML to its rehosted https URL.
 * MUST run before `emailHtmlToContent` — its tiptap sanitize clears non-http(s)
 * `cid:` srcs, so an un-rewritten inline image would lose its source. Longest cid
 * first so a cid that's a prefix of another (`logo` vs `logo2`) can't corrupt it.
 */
function rewriteCidReferences(html: string, cidMap: Map<string, string>): string {
  let out = html
  for (const [cid, url] of [...cidMap].sort((a, b) => b[0].length - a[0].length)) {
    const escaped = cid.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    out = out.replace(new RegExp(`cid:${escaped}`, 'gi'), url)
  }
  return out
}

/**
 * Rehost inbound MIME attachment parts to workspace storage. Inline images whose
 * `cid:` is referenced in the HTML are rewritten into the body (they render as
 * inline images once `emailHtmlToContent` runs on the rewritten HTML); every
 * other part becomes a discrete `attachments[]` entry.
 *
 * Fail-soft by design: an inline image over the size cap or whose bytes don't
 * match its declared type, a refused or over-count attachment, or a failed
 * upload is dropped with a log line — a single bad part never fails the whole
 * ingest. Inline images upload via `uploadImageBuffer` (the allow-list primitive
 * the content rehoster uses); discrete attachments go through `storeFile`, the
 * same pipeline as the composers, recorded as the sender's files so the
 * message write can attach them.
 */
async function rehostInboundMedia(
  parsed: ParsedInboundEmail,
  senderPrincipalId: PrincipalId | null
): Promise<RehostedInboundMedia> {
  const parts = parsed.attachments ?? []
  if (parts.length === 0) return { html: parsed.html, attachments: [] }
  if (!isS3Usable()) {
    log.warn({ count: parts.length }, 'inbound email media dropped: storage not configured')
    return { html: parsed.html, attachments: [] }
  }

  let html = parsed.html
  const cidMap = new Map<string, string>()
  const attachments: ConversationAttachment[] = []
  let uploads = 0

  for (const part of parts) {
    if (part.bytes.length === 0) continue
    // Total-upload ceiling: gates inline images too, so a message referencing
    // thousands of tiny cid: images can't amplify into thousands of S3 puts.
    if (uploads >= MAX_INBOUND_UPLOADS) {
      log.warn({ name: part.filename }, 'inbound email part dropped: over upload budget')
      continue
    }
    const declared = canonicalizeImageMime((part.contentType || '').toLowerCase())
    const referenced = !!part.contentId && !!html && htmlReferencesCid(html, part.contentId)

    if (referenced && part.contentId) {
      // An inline image lands in the body, not the attachment tray.
      if (part.bytes.length > MAX_FILE_SIZE) {
        log.warn(
          { name: part.filename, size: part.bytes.length },
          'inbound email inline image dropped: over size cap'
        )
        continue
      }
      const sniffed = sniffImageMime(part.bytes)
      if (!sniffed || sniffed !== declared) {
        log.warn(
          { name: part.filename, declared, sniffed },
          'inbound email inline image dropped: bytes do not match declared type'
        )
        continue
      }
      try {
        const { url } = await uploadImageBuffer(part.bytes, sniffed, INBOUND_IMAGE_PREFIX)
        cidMap.set(part.contentId, url)
        uploads++
      } catch (err) {
        log.warn({ err, name: part.filename }, 'inbound email image upload failed; skipped')
      }
      continue
    }

    // Every other part is a discrete attachment, stored through the file
    // pipeline: typed from its bytes, capped per type, and refused when it is
    // an executable or script (an email sender is not a verified identity).
    if (attachments.length >= MAX_CONVERSATION_ATTACHMENTS) {
      log.warn({ name: part.filename }, 'inbound email attachment dropped: over count cap')
      continue
    }
    try {
      const row = await storeFile({
        bytes: part.bytes,
        name: part.filename || (declared.startsWith('image/') ? 'image' : 'attachment'),
        declaredType: declared || null,
        source: 'email',
        uploadedById: senderPrincipalId,
        unverifiedSender: true,
      })
      uploads++
      attachments.push(attachmentFromFile(row))
    } catch (err) {
      if (err instanceof FileRejectedError) {
        log.warn({ name: part.filename, reason: err.reason }, 'inbound email attachment refused')
      } else {
        log.warn({ err, name: part.filename }, 'inbound email attachment upload failed; skipped')
      }
    }
  }

  if (cidMap.size > 0 && html) html = rewriteCidReferences(html, cidMap)
  return { html, attachments }
}

/** Find the conversation id carried by any recipient plus-address. */
function conversationIdFromRecipients(toAddresses: string[]): string | null {
  for (const addr of toAddresses) {
    const id = conversationIdFromInboundAddress(addr)
    if (id) return id
  }
  return null
}

/** Find the verified ticket id carried by any recipient `<slug>+t…` address. */
function ticketIdFromRecipients(recipients: string[]): TicketId | null {
  for (const addr of recipients) {
    const id = ticketIdFromInboundAddress(addr)
    if (id) return id as TicketId
  }
  return null
}

/** Does any recipient claim to be ticket-destined (verified or not)? The claim
 *  is a property of the address grammar, so the channel module decides it —
 *  see `bearsTicketMarker`. Used to guarantee a forged or tampered ticket
 *  address is DROPPED, not reinterpreted as a conversation reply or opened as
 *  cold inbound. */
function recipientsBearTicketMarker(recipients: string[]): boolean {
  return recipients.some((a) => bearsTicketMarker(a))
}

/**
 * Every address this message was sent to, To and Cc alike.
 *
 * The set the ticket branch and cold inbound must BOTH decide on, because they
 * are two answers to one question and the narrower one was the guard. Cold
 * inbound has always read To ∪ Cc — a customer looping support into a thread
 * with somebody else puts the address in Cc, and reading To alone would drop
 * exactly that message — so a ticket claim that was only looked for in To left a
 * forged `<slug>+t…` address in Cc to fall through and be opened as ordinary
 * mail to the workspace address, which is the one thing the ticket guards exist
 * to prevent.
 *
 * Conversation routing deliberately still reads `To` alone: a `+c` address is a
 * reply address for one thread, and a copy of it in Cc is somebody else's
 * thread, not this message's destination.
 */
function allRecipients(parsed: ParsedInboundEmail): string[] {
  return [...parsed.toAddresses, ...parsed.ccAddresses]
}

/**
 * Route + append a parsed inbound email. Provider-neutral core shared by the
 * webhook and the IMAP poller.
 */
export async function ingestParsedEmail(parsed: ParsedInboundEmail): Promise<IngestInboundResult> {
  // Loop / auto-mail suppression before any routing. A loop, a ticket-bound
  // auto-reply, or any auto mail carrying threading context is never appended
  // — never let an autoresponder or one of our own mails looping back fan out
  // a reply or append to a thread. A truly cold auto-generated mail (a bulk
  // blast to the support address with no thread context) is instead ingested
  // and filed to Spam by the signal layer, so it stays auditable in the Spam
  // view rather than vanishing. Runs BEFORE the ticket branch too, so an
  // auto-reply to a ticket notification never appends.
  //
  // Whose mail this process is answering for. Read once, so every half of "is
  // this ours" is decided against the same workspace: the signing secret and the
  // sending domain are both fleet-wide, and either half checked without the
  // label would let a neighbour's mail pass as our own.
  const slug = currentMailSlug()
  const ourMessageIdHosts = ownMessageIdDomains()
  // THE EXACT QUESTION FIRST, and it is asked of the message's OWN id alone —
  // never of the ids it quotes, which is what threading is and what every
  // genuine reply carries. A row here means this workspace recorded that id when
  // its own mail went out, on whichever transport it went out through: no host
  // is inferred, no shape is matched, and a replier's MTA mints its own id. What
  // is left that can match is a copy of our own message travelling under its
  // original id, which is the loop shape itself: a redirect or a resend rather
  // than a forward, since forwarding composes a new message with a new id. One
  // indexed lookup per inbound message buys the one signal that survives a
  // sending provider replacing our `Message-ID`.
  const recordedOutbound =
    parsed.messageId !== null &&
    (await resolveConversationByMessageIds([parsed.messageId])) !== null
  const loop: MailLoopSignal | null = recordedOutbound
    ? 'recorded_outbound'
    : mailLoopSignal(parsed, ourMessageIdHosts, (address) => isOwnInboundAddress(address, slug))

  // The two loop signals reach two dispositions, which is the whole reason the
  // signal is a vocabulary rather than a boolean. 'own_reply_to' is a guess, so
  // the refusal vocabulary quarantines it (see 'mail_loop_suspected'); the other
  // two are facts, so nothing is kept. Suppression comes from not replying, not
  // from destroying: the quarantine files the thread to Spam inside the insert,
  // so it rings no bell, starts no SLA clock and triggers no auto-reply, and a
  // loop cannot feed itself.
  if (loop === 'own_reply_to') {
    return ingestColdInbound(parsed, { quarantineCause: 'mail_loop_suspected' })
  }
  if (loop !== null) {
    logRefusal('mail_loop', false)
    return { status: 'suppressed' }
  }

  const recipients = allRecipients(parsed)

  if (isAutoGeneratedEmail(parsed, ourMessageIdHosts)) {
    if (
      recipientsBearTicketMarker(recipients) ||
      conversationIdFromRecipients(parsed.toAddresses) !== null ||
      parsed.inReplyTo !== null ||
      parsed.references.length > 0
    ) {
      logRefusal('auto_generated', false)
      return { status: 'suppressed' }
    }
    return ingestColdInbound(parsed, { autoResponder: true })
  }

  // Ticket reply branch (D9): a signed `<slug>+t…` recipient routes straight
  // into the ticket thread. Checked BEFORE conversation routing and cold inbound
  // so a ticket address can never be reinterpreted as a conversation reply nor
  // opened as a fresh cold-inbound conversation — `ingestTicketReply` always
  // returns a terminal status. A ticket-shaped mail whose signature failed to
  // verify is still ticket-destined: drop it here rather than let a forged
  // address fall through. Asked of To ∪ Cc, the same set cold inbound reads, so
  // there is no recipient this drop can be routed around. Conversation addresses
  // (`c` marker) skip this entirely.
  const ticketId = ticketIdFromRecipients(recipients)
  if (ticketId) return ingestTicketReply(parsed, ticketId)
  if (recipientsBearTicketMarker(recipients)) {
    log.warn(
      { reason: 'unverified_ticket_address' },
      'inbound ticket reply dropped: signature did not verify'
    )
    return { status: 'no_ticket' }
  }

  // Route: plus-address first, then the deterministic-Message-ID fallback for
  // replies whose client dropped the plus-address but kept the threading chain.
  const { resolveInboundConversation } = await import('./conversation.inbound-resolve')
  let conversationId = conversationIdFromRecipients(parsed.toAddresses) as ConversationId | null
  if (!conversationId) {
    const candidates = [parsed.inReplyTo, ...parsed.references].filter(
      (id): id is string => id !== null
    )
    // Email's Message-ID map is still the correlation authority. The shared
    // pipeline is the shape; step 2 (open-by-sender) is omitted so behavior
    // does not change.
    conversationId = await resolveInboundConversation({
      lookupCorrelation: () => resolveConversationByMessageIds(candidates),
    })
  }
  // Not a reply to any existing conversation: it may be a fresh email to one of
  // our inbound routes (§4.8 Layer 2 cold inbound), else there's nothing to do.
  if (!conversationId) return ingestColdInbound(parsed)

  // Idempotency first: a redelivered message short-circuits before any other
  // read (the common retry case). The partial unique index on
  // (metadata->>'emailMessageId') is the hard backstop; this makes a retry a
  // graceful no-op instead of a unique-violation. The key is the message's own
  // Message-ID, or the delivering transport's id when it carried none — one
  // derivation, so the value looked up here and the value stored below cannot
  // come to disagree. See {@link inboundDedupeKey}.
  const dedupeKey = inboundDedupeKey(parsed)
  if (dedupeKey) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${dedupeKey}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const conversation = await db.query.conversations.findFirst({
    where: eq(conversations.id, conversationId),
  })
  if (!conversation) return { status: 'no_conversation' }

  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) {
    logRefusal('empty_body', false)
    return { status: 'empty' }
  }

  const visitorPrincipalId = conversation.visitorPrincipalId as PrincipalId
  const visitor = await db.query.principal.findFirst({
    where: eq(principal.id, visitorPrincipalId),
  })
  if (!visitor) return { status: 'no_conversation' }

  // The transport authenticates the delivery, not the SMTP sender: the signed
  // address is visible to anyone on the email thread (CC, forward), so without
  // this check any third party could inject messages attributed to the visitor.
  // The From must match an address we know for this visitor — a linked account
  // email, the principal contact email, the captured pre-chat email, or a
  // recorded channel identity that resolves to this same visitor principal.
  // realEmail() keeps synthetic anonymous placeholders out of the set; an empty
  // set with no matching identity means nothing can match.
  const linkedUser = visitor.userId
    ? await db.query.user.findFirst({ where: eq(user.id, visitor.userId) })
    : null
  const knownAddresses = new Set(
    [linkedUser?.email, visitor.contactEmail, conversation.visitorEmail]
      .map((e) => realEmail(e))
      .filter((e): e is string => e !== null)
      .map((e) => e.toLowerCase())
  )
  const sender = extractEmailAddress(parsed.from)
  if (!sender) return { status: 'from_mismatch' }
  if (!knownAddresses.has(sender)) {
    const mappedPrincipalId = await resolvePrincipalIdByEmail(sender)
    if (mappedPrincipalId !== visitorPrincipalId) return { status: 'from_mismatch' }
  }

  // Blocked people cannot reply over email either; ack (200) so the provider
  // stops retrying, mirroring the widget send gate.
  if (await isBlocked(visitorPrincipalId)) {
    logRefusal('sender_blocked', false)
    return { status: 'suppressed' }
  }

  // Same per-visitor throttle the widget send path enforces — the inbound email
  // channel must not be an unbounded back door for the offline-notification
  // fanout (a visitor mail-looping replies, or a client retrying with fresh
  // Message-IDs). Fails open on store errors. Ack (200) so the provider stops.
  try {
    await assertConversationSendRate(visitorPrincipalId)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) {
      logRefusal('rate_limited', false)
      return { status: 'rate_limited' }
    }
    throw err
  }

  const actor: Actor = {
    principalId: visitorPrincipalId,
    role: (visitor.role ?? null) as Actor['role'],
    principalType: normalizePrincipalType(visitor.type),
    segmentIds: new Set(),
  }

  // Rehost inbound media only now — after the sender is verified and the message
  // cleared the rate gate — so a forged / throttled mail never spends an upload.
  // Inline `cid:` images are rewritten into the HTML before conversion; other
  // files become discrete attachments. Convert the HTML body (rewritten) to a
  // rich doc + its plaintext mirror: text/plain keeps precedence for `content`
  // (the sender's own quote-trimmed words); the HTML supplies `contentJson` and,
  // for an HTML-only message, the `content` fallback.
  const media = await rehostInboundMedia(parsed, visitorPrincipalId)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')
  const contentJson = converted?.contentJson ?? null

  await sendVisitorMessage(
    {
      conversationId,
      content,
      metadata: { source: 'email', emailMessageId: dedupeKey ?? undefined },
      ...(media.attachments.length > 0 ? { attachments: media.attachments } : {}),
    },
    { principalId: visitorPrincipalId, displayName: visitor.displayName },
    actor,
    contentJson
  )

  return { status: 'ingested', conversationId }
}

/**
 * Cold inbound (§4.8 Layer 2): an email that isn't a reply. Only ingest it when
 * it's addressed to one of our inbound routes; otherwise it's not ours. The
 * DMARC-gated sender resolution decides attach / create-lead, then a fresh email
 * conversation is opened — accepted into the inbox, or quarantined to Spam when
 * its authentication was refused. Dedup + empty-body guards mirror the reply
 * path.
 */
async function ingestColdInbound(
  parsed: ParsedInboundEmail,
  opts: {
    autoResponder?: boolean
    /** A refusal the CALLER already decided, which this path retains rather
     *  than acts on: the thread is filed to Spam inside the insert under this
     *  cause. Set for a message the loop guard inferred is one of our own
     *  coming back; omitted for everything else, where the sender's own
     *  authentication is the only thing that can quarantine. */
    quarantineCause?: QuarantineCause
  } = {}
): Promise<IngestInboundResult> {
  const recipients = allRecipients(parsed)
  const matched = await resolveChannelAccountByRecipient(recipients)
  // A `sending` row is a From identity, not a front door, so mail addressed to
  // one is not cold inbound. The workspace's PLATFORM INBOX is a front door that
  // needs no row to exist, so it is asked next rather than instead — which is
  // what makes a workspace with nothing configured able to receive.
  //
  // Asked as a question here and answered as a WRITE further down, past every
  // gate that can refuse this message. Nothing about the row depends on the
  // sender, so there is nothing to learn by creating it early, and creating it
  // early means a blocked or throttled stranger's message still leaves the
  // workspace a permanent row behind.
  const inboundRoute = matched?.role === 'inbound' ? matched : null
  if (!inboundRoute && !addressesPlatformInbox(recipients)) return { status: 'no_conversation' }

  // Same key the reply path deduplicates on, and the same one the insert stamps.
  const dedupeKey = inboundDedupeKey(parsed)
  if (dedupeKey) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${dedupeKey}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) {
    logRefusal('empty_body', false)
    return { status: 'empty' }
  }

  // An unparseable From is the one shape with no key to throttle on, and today
  // it mints a lead with a null contact email on a conversation nobody can ever
  // reply to. Drop it, reusing from_mismatch rather than growing the result union.
  const senderEmail = normalizeSenderAddress(parsed.from)
  if (!senderEmail) {
    log.warn({ reason: 'unparseable_from' }, 'cold inbound dropped')
    return { status: 'from_mismatch' }
  }

  // Throttle BEFORE resolution — resolution is what mints a principal, so a
  // gate placed after it has already let the row be created. Both this and the
  // block check below sit after the dedupe and empty-body guards so a provider
  // redelivery never burns a token.
  try {
    await assertColdInboundRate(senderEmail)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) {
      logRefusal('rate_limited', false)
      return { status: 'rate_limited' }
    }
    throw err
  }

  // A teammate's test alias: the mail belongs to that teammate's test
  // customer, whoever sent it, and never to the sender's own identity.
  const { testAliasOwnerFor } = await import('@/lib/server/test-email-alias')
  const testOwner = await testAliasOwnerFor(recipients, currentMailSlug())
  if (testOwner) {
    return ingestTestAliasMail(parsed, testOwner, {
      inboundRoute,
      recipients,
      plainText,
      quarantineCause: opts.quarantineCause ?? null,
    })
  }

  const resolution = await resolveColdInboundSender(parsed.from, parsed.authenticationResults)

  // Blocked people cannot open a new thread by email either. Unconditional
  // rather than attach-only: a branch is more code than the one vacuous PK read
  // it would save on the create path. Placed before rehostInboundMedia so a
  // blocked sender never spends an upload — the ordering the reply and ticket
  // paths already use.
  //
  // Ahead of the quarantine decision too, and that ordering is the point: a
  // refused message is still retained for review, but a blocked sender's is
  // not. The workspace already decided it does not want this person's mail, and
  // quarantining it anyway would put it back in front of the agent who blocked
  // them.
  if (await isBlocked(resolution.principalId)) {
    logRefusal('sender_blocked', false)
    return { status: 'suppressed' }
  }

  // What the sender's authentication earned this message. A hard DMARC reject
  // no longer destroys it: it is retained in Spam under an enumerated cause,
  // where an agent can see it arrived, see why it was refused, and release it.
  // That is the ONE thing this changes. The reject verdict still confers no
  // identity (resolution above can only have minted or reused an anonymous
  // lead) and the message still never enters the normal flow.
  const authSignal = senderAuthSpamSignal(resolution.verdict)
  // The caller's refusal outranks the sender's authentication, because it is
  // the more specific thing known about this message: mail we believe is our own
  // is refused whatever its DMARC verdict says, and the cause an agent reads
  // should be the one that decided the filing.
  const quarantineCause: QuarantineCause | null =
    opts.quarantineCause ?? (authSignal === 'sender_auth_reject' ? authSignal : null)
  const quarantineNote =
    quarantineCause === 'mail_loop_suspected'
      ? 'Refused as a suspected mail loop: the message carried a reply address this workspace minted.'
      : resolution.verdict.reason

  // Rehost media after the drop gates (never upload for a blocked sender). Same
  // precedence as the reply path: text/plain owns `content`; the rewritten HTML
  // supplies `contentJson` and the HTML-only `content` fallback.
  const media = await rehostInboundMedia(parsed, resolution.principalId)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')

  // Every way out from here that leaves no conversation behind takes the lead
  // this message minted with it, so a message nobody kept leaves no person
  // behind in the database either.
  const discardMintedLead = async () => {
    if (resolution.action === 'create') {
      await cleanupColdInboundLead(resolution.principalId).catch(() => {})
    }
  }

  // The write half of the question asked at the top of this function, now past
  // every gate that can refuse the message. A workspace whose default team is
  // missing has no route to own.
  const channelAccount = inboundRoute ?? (await ensurePlatformInboundRoute(recipients))
  if (!channelAccount) {
    await discardMintedLead()
    log.warn({ reason: 'no_inbound_route' }, 'cold inbound dropped')
    return { status: 'no_conversation' }
  }

  let conversationId: ConversationId
  try {
    conversationId = await createEmailConversation({
      parsed,
      channelAccountId: channelAccount.id,
      principalId: resolution.principalId,
      unverified: resolution.unverified,
      content,
      contentJson: converted?.contentJson ?? null,
      attachments: media.attachments,
      // Filed in the insert, so there is no instant at which refused mail is
      // in the open queue. The free-text note is the MTA's own wording, or ours
      // for a refusal we decided ourselves, kept as a supplement to the
      // enumerated cause and never as a substitute for it.
      quarantine: quarantineCause ? { cause: quarantineCause, note: quarantineNote } : null,
    })
  } catch (error) {
    await discardMintedLead()
    throw error
  }

  if (quarantineCause) {
    logRefusal(quarantineCause, true)
    return { status: 'quarantined', conversationId, cause: quarantineCause }
  }

  // Spam filter, after the thread exists so a filing has something to land
  // on. Error-isolated inside (a classification failure leaves the thread in
  // triage, never breaks ingestion); the workspace trust list bypasses it.
  // The deterministic signals run first: auto-responder headers (this mail
  // arrived already flagged machine-generated) and whatever the sender's
  // authentication earned short of the quarantine above — either files to Spam
  // without spending an AI completion.
  await maybeAutoFileSpam(conversationId, {
    senderEmail,
    subject: parsed.subject,
    content,
    signals: {
      autoResponder: opts.autoResponder === true,
      senderAuthSignal: authSignal,
    },
  })
  if (opts.autoResponder !== true) {
    // Fire-and-forget on purpose — the ack must not delay the ingest response —
    // but never unhandled: a failed ack is a log line, not a process-level
    // unhandled rejection.
    void import('./conversation.auto-ack')
      .then(({ maybeSendColdInboundAck }) =>
        maybeSendColdInboundAck({
          parsed,
          conversationId,
          conversationSubject: parsed.subject,
        })
      )
      .catch((err) => log.error({ err, conversationId }, 'cold-inbound auto-ack failed'))
  }
  return { status: 'ingested', conversationId }
}

/**
 * Mail to a teammate's test alias opens a test conversation as that
 * teammate's test customer. The sender's authentication confers nothing here,
 * because the alias, not the sender, decides the identity; the thread is test
 * data, so it raises no spam classification and no acknowledgement mail.
 */
async function ingestTestAliasMail(
  parsed: ParsedInboundEmail,
  ownerPrincipalId: PrincipalId,
  opts: {
    inboundRoute: Awaited<ReturnType<typeof resolveChannelAccountByRecipient>> | null
    recipients: string[]
    plainText: string
    quarantineCause: QuarantineCause | null
  }
): Promise<IngestInboundResult> {
  const { getOrCreateTestCustomer } = await import('@/lib/server/test-customer')
  const customer = await getOrCreateTestCustomer(ownerPrincipalId, DEFAULT_LOCALE)
  const channelAccount = opts.inboundRoute ?? (await ensurePlatformInboundRoute(opts.recipients))
  if (!channelAccount) {
    log.warn({ reason: 'no_inbound_route' }, 'test alias mail dropped')
    return { status: 'no_conversation' }
  }
  const media = await rehostInboundMedia(parsed, customer.id)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    opts.plainText ||
    converted?.text ||
    (media.attachments.length > 0 ? '' : '(no plain-text body)')
  const quarantine = opts.quarantineCause
  const conversationId = await createEmailConversation({
    parsed,
    channelAccountId: channelAccount.id,
    principalId: customer.id,
    unverified: false,
    content,
    contentJson: converted?.contentJson ?? null,
    attachments: media.attachments,
    quarantine: quarantine
      ? {
          cause: quarantine,
          note: 'Refused as a suspected mail loop: the message carried a reply address this workspace minted.',
        }
      : null,
  })
  if (quarantine) {
    logRefusal(quarantine, true)
    return { status: 'quarantined', conversationId, cause: quarantine }
  }
  return { status: 'ingested', conversationId }
}

/**
 * Reply-by-email (D9): append a verified inbound email onto the ticket named by a
 * signed `<slug>+t…` recipient. Fails QUIET on every rejection — unknown /
 * deleted / non-`customer` ticket, missing requester, or a sender that isn't the
 * requester — with a structured `log.warn`, never creating a ticket or a
 * conversation and never bouncing. Only reached from `ingestParsedEmail` after the
 * RFC 3834 / loop guards and only for a signature-verified ticket address, so the
 * transport is trusted; the remaining trust step is proving the SMTP sender is the
 * requester (the signed address alone is visible to anyone CC'd on a ticket mail).
 */
async function ingestTicketReply(
  parsed: ParsedInboundEmail,
  ticketId: TicketId
): Promise<IngestInboundResult> {
  // Idempotency: a redelivered message is a graceful no-op. The append stamps
  // `metadata.emailMessageId`, so this shares the same partial unique index the
  // conversation path relies on as the hard backstop, and the same key
  // derivation so the two paths never file one message under two spellings.
  const dedupeKey = inboundDedupeKey(parsed)
  if (dedupeKey) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${dedupeKey}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  let ticket
  try {
    ticket = await loadTicketOr404(ticketId)
  } catch (err) {
    // A missing/deleted ticket is a quiet drop; a transient DB error must still
    // throw so the provider retries (mirrors the conversation path's behavior).
    if (err instanceof NotFoundError) {
      log.warn({ ticketId, reason: 'unknown_or_deleted_ticket' }, 'inbound ticket reply dropped')
      return { status: 'no_ticket' }
    }
    throw err
  }

  // Only `customer` tickets are a two-way requester thread; internal ticket types
  // have no requester to attribute an inbound reply to.
  if (ticket.type !== 'customer') {
    log.warn({ ticketId, reason: 'non_customer_ticket' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }
  const requesterPrincipalId = ticket.requesterPrincipalId as PrincipalId | null
  if (!requesterPrincipalId) {
    log.warn({ ticketId, reason: 'no_requester' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }

  // Sender verification: the From must match a known address for the requester.
  // Precedence mirrors `resolveReplyRecipient` — an identified requester's account
  // email, then the principal-level contact email. `realEmail()` keeps synthetic
  // anonymous placeholders out of the set; an empty set can never match.
  const requester = await db.query.principal.findFirst({
    where: eq(principal.id, requesterPrincipalId),
  })
  if (!requester) {
    log.warn({ ticketId, reason: 'requester_not_found' }, 'inbound ticket reply dropped')
    return { status: 'no_ticket' }
  }
  const linkedUser =
    requester.type !== 'anonymous' && requester.userId
      ? await db.query.user.findFirst({ where: eq(user.id, requester.userId) })
      : null
  const knownAddresses = new Set(
    [linkedUser?.email, requester.contactEmail]
      .map((e) => realEmail(e))
      .filter((e): e is string => e !== null)
      .map((e) => e.toLowerCase())
  )
  const sender = extractEmailAddress(parsed.from)
  if (!sender || !knownAddresses.has(sender)) {
    log.warn({ ticketId, reason: 'sender_not_requester' }, 'inbound ticket reply dropped')
    return { status: 'from_mismatch' }
  }

  // Blocked requesters cannot reply over email either; ack (drop, no bounce) so
  // the provider stops retrying, mirroring the conversation reply gate.
  if (await isBlocked(requesterPrincipalId)) {
    log.warn({ ticketId, reason: 'requester_blocked' }, 'inbound ticket reply dropped')
    logRefusal('sender_blocked', false)
    return { status: 'suppressed' }
  }

  // Same per-principal throttle the conversation reply path enforces — the
  // inbound email channel must not be an unbounded back door for the ticket
  // watcher/agent fan-out (a mail loop or a client retrying with fresh
  // Message-IDs). Fails open on store errors.
  try {
    await assertConversationSendRate(requesterPrincipalId)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) {
      logRefusal('rate_limited', false)
      return { status: 'rate_limited' }
    }
    throw err
  }

  // Quoted-history stripping is identical to the conversation reply path.
  const plainText = extractReplyText(parsed.text ?? '')
  const hasAttachmentParts = (parsed.attachments?.length ?? 0) > 0
  if (!plainText && !parsed.html && !hasAttachmentParts) {
    logRefusal('empty_body', false)
    return { status: 'empty' }
  }

  // Rehost media only now — after the sender is verified — so a forged mail never
  // spends an upload. Same content precedence as the conversation path: text/plain
  // (quote-trimmed) owns `content`; the rewritten HTML supplies `contentJson` and
  // the HTML-only `content` fallback.
  const media = await rehostInboundMedia(parsed, requesterPrincipalId)
  const converted = media.html ? emailHtmlToContent(media.html) : null
  const content =
    plainText || converted?.text || (media.attachments.length > 0 ? '' : '(no plain-text body)')

  await appendInboundTicketReply(
    ticketId,
    requesterPrincipalId,
    {
      content,
      contentJson: converted?.contentJson ?? null,
      ...(media.attachments.length > 0 ? { attachments: media.attachments } : {}),
      metadata: { source: 'email', emailMessageId: dedupeKey ?? undefined },
    },
    normalizePrincipalType(requester.type)
  )

  return { status: 'ingested_ticket', ticketId }
}

/**
 * Webhook front door: normalize a provider `email.received` event's parsed
 * `data` and ingest it. Kept as the stable entry point the Resend webhook
 * handler calls.
 */
export async function ingestInboundEmail(event: unknown): Promise<IngestInboundResult> {
  const data =
    (event && typeof event === 'object' ? (event as { data?: unknown }).data : null) ?? null
  const parsed = parseInboundEmail(data)

  // Resend's `email.received` webhook is metadata-only — it carries no text/html
  // body. When the payload has no body but exposes the provider email id, fetch
  // the full message from the Received Emails API (#320) and normalize it onto
  // the parsed shape before the provider-neutral core runs. The IMAP front door
  // never hits this (it carries the full RFC822 body, and `emailId` is null).
  // `not_found`/no-API-key → null → falls through to the normal empty-body drop;
  // any other fetch error throws → the webhook route 500s → Resend redelivers
  // (idempotent via the Message-ID dedupe + the partial unique index).
  if (!parsed.text && !parsed.html && parsed.emailId) {
    const full = await getReceivedEmail(parsed.emailId)
    if (full?.text) parsed.text = full.text
    if (full?.html) parsed.html = full.html
  }

  const result = await ingestParsedEmail(parsed)
  void import('@/lib/server/email/email-log.sink').then(({ recordInboundEmailLog }) =>
    recordInboundEmailLog({
      emailType:
        result.status === 'ingested'
          ? 'reply'
          : result.status === 'quarantined'
            ? 'rejected'
            : result.status === 'ingested_ticket'
              ? 'reply'
              : result.status === 'no_conversation'
                ? 'cold_inbound'
                : 'rejected',
      address: parsed.from ?? '',
      subject: parsed.subject,
      conversationId: 'conversationId' in result ? result.conversationId : null,
      ticketId: 'ticketId' in result ? result.ticketId : null,
      status:
        result.status === 'ingested' || result.status === 'ingested_ticket'
          ? 'received'
          : 'rejected',
      error: result.status,
      messageId: parsed.messageId,
    })
  )
  return result
}
